"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const root=path.resolve(__dirname,"..");
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),"utf8").replace(/^\uFEFF/,""));
const cp=read("ECG_EXECUTABLE_SIGNAL_INTELLIGENCE_CHECKPOINT.json");
const caps=read("ECG_CAPABILITY_REGISTRY.json");
const protocol=read("evaluation/protocols/EXECUTABLE_MEASUREMENT_CONTRACT.json");
const fixture=read("evaluation/fixtures/SYNTHETIC_RPEAK_MEASUREMENT.json");
const donors=read("ECG_DONOR_REGISTRY.json"), pkg=read("package.json");
let passed=0; const check=(n,f)=>{f();passed++;console.log("PASS "+n);};
check("checkpoint is pinned to accepted Donor 009 main",()=>{assert.strictEqual(cp.parentMainCommit,"717ade1ce6a3fa60b24e91495f577cb7a6015be6");assert.strictEqual(cp.parentMainTree,"580b84fd261376e4b428b48011bd73cbd6bab776");});
check("donor frontier is paused without changing donor completion",()=>{assert.strictEqual(cp.donorProgram.completedPrimaryDonors,9);assert.strictEqual(cp.donorProgram.pausedFrontier,"DONOR-010");assert.strictEqual(donors.completed_donors,9);assert.strictEqual(donors.next_donor_id,"DONOR-010");});
check("measurement implementation is target-owned and CI-wired",()=>{for(const p of cp.implementation)assert.ok(fs.existsSync(path.join(root,p)),p);assert.ok(pkg.scripts["test:ci"].includes("tests/signal_measurement_contract.test.js"));assert.ok(pkg.scripts["test:ci"].includes("tests/executable_signal_intelligence_checkpoint.test.js"));});
check("canonical R-peak capability is inactive evaluation implementation",()=>{const c=caps.capabilities.find(x=>x.capability_id==="ECG-CAP-EVENT-RPEAK-DETECTION");assert.ok(c);assert.strictEqual(c.canonical_target_path,"lib/signal_measurement_contract.js");assert.strictEqual(c.authority_class,"EVALUATION_NONRUNTIME");assert.strictEqual(c.runtime_status,"INACTIVE_EVALUATION_ONLY");});
check("evaluation protocol cannot claim clinical authority",()=>{assert.strictEqual(protocol.diagnosticRuntime,"GOVERNED_INACTIVE");assert.strictEqual(protocol.evidenceAdmission,"NOT_ADMITTED");assert.strictEqual(protocol.projectGold,false);assert.strictEqual(protocol.metrics,"NOT_REPORTABLE");assert.strictEqual(protocol.activation,"NOT_ELIGIBLE");assert.strictEqual(protocol.clinicalValidityInferred,false);});
check("synthetic fixture is non-clinical and non-gold",()=>{assert.strictEqual(fixture.clinicalData,false);assert.strictEqual(fixture.projectGold,false);assert.strictEqual(fixture.runtimeAuthority,false);assert.ok(fixture.fixtureId.startsWith("ECG-FIXTURE-SYNTHETIC-"));});
check("implementation verification is exact and successful",()=>{const v=cp.verification;assert.ok(/^[0-9a-f]{40}$/.test(v.implementationCandidateCommit));assert.ok(/^[0-9a-f]{40}$/.test(v.implementationCandidateTree));assert.strictEqual(v.candidateCiRunId,35264486099);assert.strictEqual(v.candidateCiConclusion,"success");assert.strictEqual(v.independentVerification,"PASS");assert.strictEqual(v.independentFullTargetSuite,"PASS");});
check("clinical control boundary was not changed",()=>{assert.strictEqual(cp.clinicalControlChanged,false);assert.strictEqual(cp.clinicalAuthorityAdded,false);assert.strictEqual(cp.diagnosticRuntime,"GOVERNED_INACTIVE");assert.strictEqual(cp.activation,"NOT_ELIGIBLE");});
check("automatic delineation and diagnosis remain explicitly unimplemented",()=>{const text=protocol.notImplemented.join(" ").toLowerCase();assert.ok(text.includes("validated automatic p/qrs/t delineation"));assert.ok(text.includes("rhythm diagnosis"));assert.ok(text.includes("morphology diagnosis"));});
check("checkpoint status is stage-safe",()=>{assert.ok(new Set(["VERIFIED_IMPLEMENTATION_EVIDENCE_BOUND","PROMOTED_PENDING_TARGET_MAIN_CI","ACCEPTED_ON_MAIN"]).has(cp.status));});
console.log(JSON.stringify({schema:"ekg-executable-signal-intelligence-checkpoint-tests-v1",pass:true,passed,total:passed,completedDonors:donors.completed_donors,nextDonor:donors.next_donor_id,diagnosticRuntime:cp.diagnosticRuntime,evidenceAdmission:cp.evidenceAdmission,metrics:cp.metrics,activation:cp.activation,clinicalValidity:cp.clinicalValidity,clinicalAuthorityAdded:false}));
