from __future__ import annotations
import copy,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3]; GEN=ROOT/"clinical_control"/"v12_1_candidate"/"validation_generated"
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path); mod=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(mod); return mod
m=load("engineering_release_candidate",GEN/"engineering_release_candidate.py")
fixture=json.loads((GEN/"EP5_PKT07_RELEASE_CANDIDATE_FIXTURES.json").read_text(encoding="utf-8"))
passed=0
def check(name,cond):
 global passed
 if not cond: raise AssertionError(name)
 passed+=1
def raises(name,fn,expected):
 try: fn(); ok=False
 except ValueError as exc: ok=str(exc)==expected
 check(name,ok)

# Exact packet/accepted lineage.
check("schema",m.SCHEMA=="ekg-ep5-pkt07-release-candidate-v1");check("packet",m.PACKET_ID=="PKT-EP5-07");check("packet sha",m.PACKET_SHA256=="f542e48060490806f632eadd8f823c2433d20c171d00e7b2e743429245b11aef")
check("baseline commit",m.BASELINE_COMMIT=="5a111da7a116327b717f85fa153a71f1606564da");check("baseline tree",m.BASELINE_TREE=="e14b3bdc25005b3c5e4624bb852bd6638200ac86");check("stage2",m.STAGE2_RECEIPT=="6d90ee07819f1a269a239fcb969cf4d479dc3d809a3e637c9b675c8831363d7a")
check("ep5 packet",m.ACCEPTED_EP5_PKT06["packet_receipt_sha256"]=="c9811852cb5341a75f2bcb0182fb299cf2976b7289adf48e7e62b7ef58bd096c");check("ep5 verify",m.ACCEPTED_EP5_PKT06["verification_receipt_sha256"]=="c79206774c98388f208699a916984cf43806631f92eb4a9fac32b6ea1ec1d724");check("ep5 not admitted",m.ACCEPTED_EP5_PKT06["evidence_admission_state"]=="NOT_ADMITTED");check("ep5 zero gold",m.ACCEPTED_EP5_PKT06["approved_adjudicated_gold_count"]==0);check("ep5 inactive",m.ACCEPTED_EP5_PKT06["diagnostic_runtime"]=="GOVERNED_INACTIVE")
check("ep6 commit",m.ACCEPTED_EP6_PKT06["source_commit"]=="b9a511319eaae9b04eafa319b25ac4f549a45081");check("ep6 packet",m.ACCEPTED_EP6_PKT06["packet_receipt_sha256"]=="5bbc2713c016dfbe50ff0723bfab745624e35de96063d402bb66d4e4c23e6125");check("ep6 verify",m.ACCEPTED_EP6_PKT06["verification_receipt_sha256"]=="d7b1773fc184402171de0aee300c0330cf5ce3be711c9de2293e4c07d563a93a");check("ep6 none",m.ACCEPTED_EP6_PKT06["live_evidence_candidate_state"]=="NONE");check("ep6 not admitted",m.ACCEPTED_EP6_PKT06["evidence_admission_state"]=="NOT_ADMITTED");check("ep6 sim",m.ACCEPTED_EP6_PKT06["review_capability_proof_is_simulation"] is True)
check("blockers",m.ACTIVATION_BLOCKERS==("NO_ADMITTED_GOVERNED_CLINICAL_GOLD","METRICS_NOT_REPORTABLE","NO_SEPARATE_GOVERNED_ACTIVATION_AUTHORITY"));check("limitations",len(m.LIMITATIONS)==6);check("states",m.RELEASE_STATES==("ENGINEERING_READY_INACTIVE","BLOCKED","REVOKED"));check("rev triggers",len(m.REVOCATION_TRIGGERS)==10)
check("fixture schema",fixture["schema"]=="ekg-ep5-pkt07-release-candidate-fixtures-v1");check("fixture count",len(fixture["scenarios"])==12);check("fixture synthetic",fixture["synthetic_only"] is True)
for k in ["phi_included","raw_clinical_payloads_included","credentials_included","clinical_gold"]:check("fixture false "+k,fixture[k] is False)

nominal=m.create_release_candidate();check("nominal valid",m.validate_release_candidate(nominal));check("nominal deterministic",nominal==m.create_release_candidate());check("state",nominal["state"]=="ENGINEERING_READY_INACTIVE");check("no invalidations",nominal["invalidations"]==[]);check("blockers exact",nominal["activation_blockers"]==list(m.ACTIVATION_BLOCKERS));check("limitations exact",nominal["limitations"]==list(m.LIMITATIONS));check("engineering ready",nominal["engineering_release_ready"] is True and nominal["integration_ready"] is True);check("manifest hash",len(nominal["manifest_identity_sha256"])==64);check("candidate hash",len(nominal["release_candidate_sha256"])==64)
for k in ["activation_authorized","runtime_activation_performed","candidate_active","separate_governed_activation_authority_present","diagnostic_performance_reporting_allowed","clinical_accuracy_claimed","engineering_release_is_clinical_validity","metadata_freshness_is_clinical_validity","source_substitution_allowed","automatic_previous_version_fallback_allowed","clinical_authority_transfer","phi_included","raw_clinical_payloads_included","credentials_included"]:check("nominal false "+k,nominal[k] is False)
check("nominal runtime",nominal["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("nominal admission",nominal["evidence_admission_state"]=="NOT_ADMITTED");check("nominal zero",nominal["approved_adjudicated_gold_count"]==0);check("nominal metrics",nominal["metric_maturity"]=="NOT_REPORTABLE");check("nominal eligibility",nominal["activation_eligibility"]=="NOT_ELIGIBLE");check("nominal validity",nominal["clinical_validity"]=="NOT_INFERRED");check("nominal evidence authority",nominal["evidence_runtime_authority"]=="NON_RUNTIME_AUTHORITY");check("nominal immutable",nominal["immutable"] is True)

# Every invalidation blocks while preserving inactive/non-clinical truth.
flag_to_reason={"receipt_drift":"RECEIPT_DRIFT","evidence_state_drift":"EVIDENCE_STATE_DRIFT","gold_count_drift":"GOLD_COUNT_DRIFT","metric_maturity_drift":"METRIC_MATURITY_DRIFT","activation_authority_drift":"ACTIVATION_AUTHORITY_DRIFT","runtime_activation_attempt":"RUNTIME_ACTIVATION_ATTEMPT","source_substitution_attempt":"SOURCE_SUBSTITUTION","clinical_validity_escalation_attempt":"CLINICAL_VALIDITY_ESCALATION","provenance_tamper":"PROVENANCE_TAMPER","manifest_tamper":"MANIFEST_TAMPER"}
for flag,reason in flag_to_reason.items():
 x=m.create_release_candidate(**{flag:True})
 check(flag+" state",x["state"]=="BLOCKED");check(flag+" reason",x["invalidations"]==[reason]);check(flag+" valid",m.validate_release_candidate(x));check(flag+" no ready",x["engineering_release_ready"] is False and x["integration_ready"] is False);check(flag+" blockers",x["activation_blockers"]==list(m.ACTIVATION_BLOCKERS));check(flag+" zero",x["approved_adjudicated_gold_count"]==0);check(flag+" metrics",x["metric_maturity"]=="NOT_REPORTABLE");check(flag+" not eligible",x["activation_eligibility"]=="NOT_ELIGIBLE");check(flag+" inactive",x["diagnostic_runtime"]=="GOVERNED_INACTIVE" and x["candidate_active"] is False);check(flag+" no auth",x["activation_authorized"] is False and x["clinical_authority_transfer"] is False);check(flag+" no phi",x["phi_included"] is False and x["raw_clinical_payloads_included"] is False);check(flag+" no claim",x["diagnostic_performance_reporting_allowed"] is False and x["clinical_accuracy_claimed"] is False);check(flag+" validity",x["clinical_validity"]=="NOT_INFERRED");check(flag+" hash",len(x["release_candidate_sha256"])==64)

# Multiple invalidations sort deterministically.
multi=m.create_release_candidate(receipt_drift=True,manifest_tamper=True,source_substitution_attempt=True);check("multi blocked",multi["state"]=="BLOCKED");check("multi sorted",multi["invalidations"]==sorted(["RECEIPT_DRIFT","MANIFEST_TAMPER","SOURCE_SUBSTITUTION"]));check("multi deterministic",multi==m.create_release_candidate(receipt_drift=True,manifest_tamper=True,source_substitution_attempt=True))
# Type/tamper validation.
raises("bad bool",lambda:m.create_release_candidate(receipt_drift="yes"),"RECEIPT_DRIFT_BOOLEAN_REQUIRED")
for key,value in [("state","ACTIVE"),("approved_adjudicated_gold_count",1),("diagnostic_runtime","ACTIVE"),("clinical_validity","VALIDATED"),("release_candidate_sha256","0"*64)]:
 bad=copy.deepcopy(nominal);bad[key]=value;check("tamper "+key,m.validate_release_candidate(bad) is False)

# Restart/recovery is exact and inactive only.
recovery=m.restart_recovery_candidate(nominal);check("recovery state",recovery["state"]=="RECOVERED_INACTIVE");check("recovery source",recovery["source_release_candidate_sha256"]==nominal["release_candidate_sha256"]);check("recovery exact",recovery["exact_reproduction"] is True);check("recovery no replay",recovery["replay_prior_packets"] is False);check("recovery no raw",recovery["raw_clinical_payloads_loaded"] is False);check("recovery inactive",recovery["runtime_activation_performed"] is False and recovery["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("recovery no authority",recovery["clinical_authority_transfer"] is False);check("recovery hash",len(recovery["recovery_sha256"])==64);check("recovery deterministic",recovery==m.restart_recovery_candidate(nominal))
raises("blocked recovery",lambda:m.restart_recovery_candidate(m.create_release_candidate(receipt_drift=True)),"RELEASE_CANDIDATE_NOT_RECOVERABLE")

# Every revocation trigger creates append-only inactive revocation evidence.
revocations=[]
for trigger in m.REVOCATION_TRIGGERS:
 rv=m.revoke_release_candidate(nominal,trigger=trigger,reason="Synthetic governed revocation: "+trigger);revocations.append(rv)
 check("rv state "+trigger,rv["state"]=="REVOKED");check("rv trigger "+trigger,rv["trigger"]==trigger);check("rv append "+trigger,rv["append_only"] is True);check("rv preserve "+trigger,rv["historical_candidate_preserved"] is True);check("rv inactive "+trigger,rv["runtime_activation_performed"] is False and rv["candidate_active"] is False and rv["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("rv validity "+trigger,rv["clinical_validity"]=="NOT_INFERRED");check("rv no authority "+trigger,rv["clinical_authority_transfer"] is False);check("rv safe "+trigger,rv["phi_included"] is False and rv["raw_clinical_payloads_included"] is False);check("rv hash "+trigger,len(rv["revocation_receipt_sha256"])==64);check("rv deterministic "+trigger,rv==m.revoke_release_candidate(nominal,trigger=trigger,reason="Synthetic governed revocation: "+trigger))
raises("bad trigger",lambda:m.revoke_release_candidate(nominal,trigger="INVENTED",reason="x"),"REVOCATION_TRIGGER_UNSUPPORTED");raises("bad reason",lambda:m.revoke_release_candidate(nominal,trigger="MANIFEST_TAMPER",reason=""),"REVOCATION_REASON_INVALID")

# Downstream descriptor is status-only and preserves Platform authority.
desc=m.downstream_release_descriptor(nominal);check("desc state",desc["state"]=="ENGINEERING_READY_INACTIVE");check("desc ready",desc["engineering_release_ready"] is True and desc["integration_ready"] is True);check("desc blockers",desc["activation_blockers"]==list(m.ACTIVATION_BLOCKERS));check("desc limits",desc["limitations"]==list(m.LIMITATIONS));check("desc admission",desc["evidence_admission_state"]=="NOT_ADMITTED");check("desc zero",desc["approved_adjudicated_gold_count"]==0);check("desc metrics",desc["metric_maturity"]=="NOT_REPORTABLE");check("desc eligibility",desc["activation_eligibility"]=="NOT_ELIGIBLE");check("desc inactive",desc["activation_authorized"] is False and desc["diagnostic_runtime"]=="GOVERNED_INACTIVE" and desc["candidate_active"] is False);check("desc evidence authority",desc["evidence_runtime_authority"]=="NON_RUNTIME_AUTHORITY");check("desc validity",desc["clinical_validity"]=="NOT_INFERRED");check("desc no claims",desc["diagnostic_performance_reporting_allowed"] is False and desc["clinical_accuracy_claimed"] is False);check("desc no authority",desc["clinical_authority_transfer"] is False);check("desc safe",desc["phi_included"] is False and desc["raw_clinical_payloads_included"] is False and desc["credentials_included"] is False);check("desc platform authority",desc["platform_owner_shell_authority_preserved"] is True);check("desc hash",len(desc["descriptor_sha256"])==64);check("desc deterministic",desc==m.downstream_release_descriptor(nominal))
rev_desc=m.downstream_release_descriptor(nominal,revocations[-1]);check("rev desc",rev_desc["state"]=="REVOKED" and rev_desc["engineering_release_ready"] is False and rev_desc["integration_ready"] is False);check("rev desc inactive",rev_desc["diagnostic_runtime"]=="GOVERNED_INACTIVE" and rev_desc["activation_authorized"] is False)
bad_rv=copy.deepcopy(revocations[-1]);bad_rv["revocation_receipt_sha256"]="0"*64;raises("forged revocation",lambda:m.downstream_release_descriptor(nominal,bad_rv),"REVOCATION_INVALID")

# Cross-host portability and non-authoritative presentation metadata.
lf=b"alpha\nbeta\n";crlf=b"alpha\r\nbeta\r\n";drift=b"alpha\ngamma\n";port=m.git_object_portability(lf,crlf);check("port match",port["repository_content_match"] is True);check("port newline",port["newline_translation_only"] is True);check("port authority",port["authority_basis"]=="GIT_OBJECT_BYTES");check("port locals",all(port[k] is False for k in ["host_path_authoritative","machine_name_authoritative","shell_presentation_authoritative","timestamps_authoritative","ui_presentation_authoritative"]));check("port hash",len(port["portability_sha256"])==64);check("port drift",m.git_object_portability(lf,drift)["repository_content_match"] is False);raises("port bytes",lambda:m.git_object_portability("x",lf),"PORTABILITY_BYTES_REQUIRED")
# No activation/admission callable exists.
check("no activation callable",not hasattr(m,"activate_runtime") and not hasattr(m,"activate_candidate") and not hasattr(m,"admit_clinical_gold") and not hasattr(m,"admit_evidence"))
result={"schema":"ekg-ep5-pkt07-release-candidate-tests-v1","packet_id":m.PACKET_ID,"pass":True,"passed":passed,"total":passed,"baseline_commit":m.BASELINE_COMMIT,"baseline_tree":m.BASELINE_TREE,"state":nominal["state"],"release_candidate_sha256":nominal["release_candidate_sha256"],"manifest_identity_sha256":nominal["manifest_identity_sha256"],"recovery_sha256":recovery["recovery_sha256"],"descriptor_sha256":desc["descriptor_sha256"],"activation_blockers":nominal["activation_blockers"],"engineering_release_ready":True,"integration_ready":True,"evidence_admission_state":"NOT_ADMITTED","approved_adjudicated_gold_count":0,"metric_maturity":"NOT_REPORTABLE","activation_eligibility":"NOT_ELIGIBLE","activation_authorized":False,"runtime_activation_performed":False,"candidate_active":False,"diagnostic_runtime":"GOVERNED_INACTIVE","evidence_runtime_authority":"NON_RUNTIME_AUTHORITY","clinical_validity":"NOT_INFERRED","diagnostic_performance_reporting_allowed":False,"clinical_accuracy_claimed":False,"clinical_authority_transfer":False,"phi_included":False,"raw_clinical_payloads_included":False}
print(json.dumps(result,sort_keys=True))
