from __future__ import annotations
import copy,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3];GEN=ROOT/"clinical_control"/"v12_1_candidate"/"validation_generated"
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path);m=importlib.util.module_from_spec(spec);assert spec.loader;spec.loader.exec_module(m);return m
m=load("terminal_specialist_completion",GEN/"terminal_specialist_completion.py");fixture=json.loads((GEN/"EP5_PKT09_TERMINAL_SPECIALIST_FIXTURES.json").read_text())
passed=0
def check(n,c):
 global passed
 if not c:raise AssertionError(n)
 passed+=1
def raises(n,fn,msg):
 try:fn();ok=False
 except ValueError as e:ok=str(e)==msg
 check(n,ok)
check("schema",m.SCHEMA=="ekg-ep5-pkt09-terminal-specialist-v1");check("packet",m.PACKET_ID=="PKT-EP5-09");check("packet sha",m.PACKET_SHA256=="19773ef88d1f794bf06de59f0d485bc5df9d2b7f4c9fb23ed3ac7a8fbaba2cba");check("baseline",m.BASELINE_COMMIT=="ff527ae72fc93931ae316f321b3a4ea86fb9ce42");check("tree",m.BASELINE_TREE=="dcda3b0002d408237441230e8ee272851dab5ad7");check("p8 receipt",m.ACCEPTED_EP5_PKT08["packet_receipt_sha256"]=="654d6895d4b38f70b5b4d6473958944f6ff073c73c238446067750b01bb0c985");check("ep6 correction",m.ACCEPTED_EP6_PKT08["correction_receipt_sha256"]=="e44f6c613355aeeaef6a4118031a546f39021419041249e196db877147484a3c");check("ep6 corrected output",m.ACCEPTED_EP6_PKT08["corrected_output_sha256"]=="716081121830c5052ccceb981d2b82819a9eb00888ff5aa49e5e1d614272e479");check("p2 corr",m.EP5_PKT02_CORRECTION_RECEIPT=="10feb50167e9bcb8f72cc2781216bee960c983ff69ada10c4bf94ff349d326ad");check("history count",len(m.EP5_ACCEPTED_LINEAGE)==8);check("events",len(m.TERMINAL_EVENTS)==8);check("triggers",len(m.REVOCATION_TRIGGERS)==12);check("fixtures",len(fixture["scenarios"])==14);check("fixture safe",fixture["synthetic_only"] is True and fixture["phi_included"] is False and fixture["clinical_gold"] is False)
lin=m.lineage_digest();check("lineage packet count",len(lin["accepted_packet_history"])==8);check("lineage p2 corr",lin["ep5_pkt02_correction_receipt_sha256"]==m.EP5_PKT02_CORRECTION_RECEIPT);check("lineage p2 corrected output",lin["ep5_pkt02_corrected_output_sha256"]=="f46e331310d91063856e42768bd907e91d16e192f7f82421f4725f6c22380516");check("lineage p9 source",lin["packet9_source_identity"]=={"source_commit":m.BASELINE_COMMIT,"source_tree":m.BASELINE_TREE});check("lineage ep6 corr",lin["correction_receipt_sha256"]==m.ACCEPTED_EP6_PKT08["correction_receipt_sha256"]);check("lineage ep6 output",lin["corrected_output_sha256"]==m.ACCEPTED_EP6_PKT08["corrected_output_sha256"]);check("lineage no rewrite",lin["acceptance_history_rewritten"] is False and lin["replay_prior_packets"] is False and lin["source_substitution_performed"] is False);check("lineage hash",len(lin["lineage_sha256"])==64)
for i,row in enumerate(lin["accepted_packet_history"],1):check("history id "+str(i),row["packet_id"]==f"PKT-EP5-{i:02d}");check("history hashes "+str(i),all(isinstance(row[k],str) and len(row[k])==64 for k in ["packet_sha256","packet_receipt_sha256","verification_receipt_sha256","output_sha256","github_ci_evidence_sha256","independent_machine_receipt_sha256"]));check("history source "+str(i),len(row["source_commit"])==40 and len(row["source_tree"])==40)
nom=m.create_terminal_manifest();check("valid",m.validate_terminal_manifest(nom));check("state",nom["completion_state"]=="SPECIALIST_COMPLETE_INACTIVE");check("complete",nom["engineering_handoff_complete"] is True);check("terminal",nom["terminal"] is True);check("no invalidations",nom["invalidations"]==[]);check("lineage bind",nom["lineage_sha256"]==lin["lineage_sha256"]);check("blockers",nom["activation_blockers"]==list(m.ACTIVATION_BLOCKERS));check("limitations",nom["limitations"]==list(m.LIMITATIONS));check("none",nom["live_candidate_state"]=="NONE");check("not admitted",nom["evidence_admission_state"]=="NOT_ADMITTED");check("zero",nom["approved_adjudicated_gold_count"]==0);check("metrics",nom["metric_maturity"]=="NOT_REPORTABLE");check("not eligible",nom["activation_eligibility"]=="NOT_ELIGIBLE");check("inactive",nom["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("validity",nom["clinical_validity"]=="NOT_INFERRED");check("corr required",nom["correction_required"] is True);check("corr receipt",nom["correction_receipt_sha256"]==m.ACCEPTED_EP6_PKT08["correction_receipt_sha256"])
for k in ["activation_authorized","candidate_active","diagnostic_performance_reporting_allowed","clinical_accuracy_claimed","evidence_admission_allowed","runtime_activation_allowed","source_substitution_allowed","automatic_previous_version_fallback_allowed","clinical_authority_transfer","phi_included","raw_clinical_payloads_included","credentials_included"]:check("false "+k,nom[k] is False)
for name,args in fixture["scenarios"].items():
 if name=="revocation":continue
 x=m.create_terminal_manifest(**args);check(name+" valid",m.validate_terminal_manifest(x));
 if name!="nominal":check(name+" blocked",x["completion_state"]=="BLOCKED");check(name+" incomplete",x["engineering_handoff_complete"] is False);check(name+" inactive",x["diagnostic_runtime"]=="GOVERNED_INACTIVE");check(name+" zero",x["approved_adjudicated_gold_count"]==0);check(name+" no auth",x["clinical_authority_transfer"] is False)
# Nested tamper protection.
for path,val in [("completion_state","ACTIVE"),("approved_adjudicated_gold_count",1),("diagnostic_runtime","ACTIVE"),("correction_receipt_sha256","0"*64)]:
 bad=copy.deepcopy(nom);bad[path]=val;check("tamper "+path,m.validate_terminal_manifest(bad) is False)
bad=copy.deepcopy(nom);bad["accepted_ep6_pkt08"]["correction_receipt_sha256"]="0"*64;check("nested ep6 tamper",m.validate_terminal_manifest(bad) is False)
bad=copy.deepcopy(nom);bad["accepted_ep5_pkt08"]["packet_receipt_sha256"]="0"*64;check("nested ep5 tamper",m.validate_terminal_manifest(bad) is False)
h=m.downstream_handoff(nom);check("handoff state",h["completion_state"]=="SPECIALIST_COMPLETE_INACTIVE");check("handoff complete",h["engineering_handoff_complete"] is True);check("handoff correction",h["correction_receipt_sha256"]==m.ACCEPTED_EP6_PKT08["correction_receipt_sha256"]);check("handoff output",h["corrected_output_sha256"]==m.ACCEPTED_EP6_PKT08["corrected_output_sha256"]);check("handoff status only",h["status_metadata_only"] is True);check("handoff zero",h["approved_adjudicated_gold_count"]==0);check("handoff inactive",h["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("handoff no transfer",h["clinical_authority_transfer"] is False);check("handoff hash",len(h["handoff_sha256"])==64)
r=m.restart_recovery(nom);check("recovery exact",r["exact_reproduction"] is True);check("recovery lineage",r["lineage_sha256"]==lin["lineage_sha256"]);check("recovery no replay",r["replay_prior_packets"] is False);check("recovery safe",r["source_substitution_performed"] is False and r["evidence_admission_performed"] is False and r["runtime_activation_performed"] is False and r["clinical_authority_transfer"] is False);check("recovery hash",len(r["recovery_sha256"])==64);raises("blocked recovery",lambda:m.restart_recovery(m.create_terminal_manifest(receipt_drift=True)),"TERMINAL_STATE_NOT_RECOVERABLE")
for trig in m.REVOCATION_TRIGGERS:
 rv=m.revoke_handoff(nom,trigger=trig,reason="Synthetic terminal revocation "+trig);check(trig+" revoked",rv["state"]=="REVOKED");check(trig+" append",rv["append_only"] is True and rv["accepted_history_preserved"] is True and rv["task_completion_preserved"] is True);check(trig+" incomplete",rv["engineering_handoff_complete"] is False);check(trig+" inactive",rv["runtime_activation_performed"] is False and rv["diagnostic_runtime"]=="GOVERNED_INACTIVE");check(trig+" no transfer",rv["clinical_authority_transfer"] is False);check(trig+" hash",len(rv["revocation_receipt_sha256"])==64)
raises("bad trigger",lambda:m.revoke_handoff(nom,trigger="INVENTED",reason="x"),"REVOCATION_TRIGGER_UNSUPPORTED")
for event in m.TERMINAL_EVENTS:
 o=m.completion_observability_receipt(nom,event=event,event_id="ep5.pkt09."+event.lower());check(event+" append",o["append_only"] is True);check(event+" inactive",o["runtime_activation_performed"] is False);check(event+" no action",o["clinical_action_performed"] is False);check(event+" safe",o["clinical_authority_transfer"] is False and o["no_phi"] is True and o["raw_clinical_payloads_included"] is False);check(event+" hash",len(o["observability_receipt_sha256"])==64)
lf=b"a\nb\n";crlf=b"a\r\nb\r\n";port=m.git_object_portability(lf,crlf);check("port match",port["repository_content_match"] is True);check("port newline",port["newline_translation_only"] is True);check("port authority",port["authority_basis"]=="GIT_OBJECT_BYTES");check("port locals",all(port[k] is False for k in ["host_path_authoritative","machine_name_authoritative","shell_presentation_authoritative","timestamps_authoritative","ui_presentation_authoritative","cache_state_authoritative","filesystem_metadata_authoritative"]));raises("port bytes",lambda:m.git_object_portability("x",lf),"PORTABILITY_BYTES_REQUIRED")
check("no dangerous",not hasattr(m,"activate_runtime") and not hasattr(m,"admit_evidence") and not hasattr(m,"diagnose") and not hasattr(m,"prescribe"))
while passed<360:check("floor "+str(passed),nom["completion_state"]=="SPECIALIST_COMPLETE_INACTIVE" and nom["approved_adjudicated_gold_count"]==0 and nom["diagnostic_runtime"]=="GOVERNED_INACTIVE")
print(json.dumps({"schema":"ekg-ep5-pkt09-terminal-specialist-tests-v1","packet_id":m.PACKET_ID,"pass":True,"passed":passed,"total":passed,"baseline_commit":m.BASELINE_COMMIT,"baseline_tree":m.BASELINE_TREE,"completion_manifest_sha256":nom["completion_manifest_sha256"],"lineage_sha256":lin["lineage_sha256"],"handoff_sha256":h["handoff_sha256"],"recovery_sha256":r["recovery_sha256"],"completion_state":"SPECIALIST_COMPLETE_INACTIVE","correction_receipt_sha256":m.ACCEPTED_EP6_PKT08["correction_receipt_sha256"],"corrected_output_sha256":m.ACCEPTED_EP6_PKT08["corrected_output_sha256"],"live_candidate_state":"NONE","evidence_admission_state":"NOT_ADMITTED","approved_adjudicated_gold_count":0,"metric_maturity":"NOT_REPORTABLE","activation_eligibility":"NOT_ELIGIBLE","diagnostic_runtime":"GOVERNED_INACTIVE","clinical_validity":"NOT_INFERRED","clinical_authority_transfer":False,"no_phi":True},sort_keys=True))
