from __future__ import annotations
import copy,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3]; GEN=ROOT/"clinical_control"/"v12_1_candidate"/"validation_generated"
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path); mod=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(mod); return mod
m=load("terminal_specialist_completion",GEN/"terminal_specialist_completion.py")
fixture=json.loads((GEN/"EP5_PKT09_TERMINAL_SPECIALIST_FIXTURES.json").read_text())
passed=0
def check(n,c):
 global passed
 if not c: raise AssertionError(n)
 passed+=1
def raises(n,fn,e):
 try: fn(); ok=False
 except ValueError as x: ok=str(x)==e
 check(n,ok)
check('schema',m.SCHEMA=='ekg-ep5-pkt09-terminal-specialist-v1');check('packet',m.PACKET_ID=='PKT-EP5-09');check('packet sha',m.PACKET_SHA256=='19773ef88d1f794bf06de59f0d485bc5df9d2b7f4c9fb23ed3ac7a8fbaba2cba');check('baseline',m.BASELINE_COMMIT=='ff527ae72fc93931ae316f321b3a4ea86fb9ce42');check('tree',m.BASELINE_TREE=='dcda3b0002d408237441230e8ee272851dab5ad7');check('stage2',m.STAGE2_RECEIPT=='6d90ee07819f1a269a239fcb969cf4d479dc3d809a3e637c9b675c8831363d7a')
check('p8 receipt',m.ACCEPTED_EP5_PKT08['packet_receipt_sha256']=='654d6895d4b38f70b5b4d6473958944f6ff073c73c238446067750b01bb0c985');check('p8 verify',m.ACCEPTED_EP5_PKT08['verification_receipt_sha256']=='79f8e360d37b825cbab8ea300709fd3f3f3510a2c95d40d62d392e4c86907397');check('ep6 correction',m.ACCEPTED_EP6_PKT08['correction_receipt_sha256']=='e44f6c613355aeeaef6a4118031a546f39021419041249e196db877147484a3c');check('ep6 corrected output',m.ACCEPTED_EP6_PKT08['corrected_output_sha256']=='716081121830c5052ccceb981d2b82819a9eb00888ff5aa49e5e1d614272e479');check('blockers',m.ACTIVATION_BLOCKERS==('NO_ADMITTED_GOVERNED_CLINICAL_GOLD','METRICS_NOT_REPORTABLE','NO_SEPARATE_GOVERNED_ACTIVATION_AUTHORITY'));check('limits',len(m.LIMITATIONS)==6);check('events',len(m.TERMINAL_EVENTS)==8);check('triggers',len(m.REVOCATION_TRIGGERS)==12);check('fixture count',len(fixture['scenarios'])==14);check('fixture safe',fixture['synthetic_only'] is True and fixture['phi_included'] is False and fixture['clinical_gold'] is False)
lineage=m.lineage_digest();check('lineage correction required',lineage['correction_required'] is True);check('lineage correction receipt',lineage['correction_receipt_sha256']==m.ACCEPTED_EP6_PKT08['correction_receipt_sha256']);check('lineage corrected output',lineage['corrected_output_sha256']==m.ACCEPTED_EP6_PKT08['corrected_output_sha256']);check('lineage no rewrite',lineage['acceptance_history_rewritten'] is False);check('lineage no replay',lineage['replay_prior_packets'] is False);check('lineage hash',len(lineage['lineage_sha256'])==64);check('lineage deterministic',lineage==m.lineage_digest())
nom=m.create_terminal_manifest();check('nom valid',m.validate_terminal_manifest(nom));check('nom deterministic',nom==m.create_terminal_manifest());check('complete state',nom['completion_state']=='SPECIALIST_COMPLETE_INACTIVE');check('handoff complete',nom['engineering_handoff_complete'] is True);check('terminal',nom['terminal'] is True);check('no invalidations',nom['invalidations']==[]);check('lineage bound',nom['lineage_sha256']==lineage['lineage_sha256']);check('correction bound',nom['correction_receipt_sha256']==m.ACCEPTED_EP6_PKT08['correction_receipt_sha256']);check('corrected output bound',nom['corrected_output_sha256']==m.ACCEPTED_EP6_PKT08['corrected_output_sha256']);check('none candidate',nom['live_candidate_state']=='NONE');check('not admitted',nom['evidence_admission_state']=='NOT_ADMITTED');check('zero gold',nom['approved_adjudicated_gold_count']==0);check('metrics',nom['metric_maturity']=='NOT_REPORTABLE');check('eligibility',nom['activation_eligibility']=='NOT_ELIGIBLE');check('inactive',nom['diagnostic_runtime']=='GOVERNED_INACTIVE');check('validity',nom['clinical_validity']=='NOT_INFERRED');check('evidence authority',nom['evidence_runtime_authority']=='NON_RUNTIME_AUTHORITY');check('manifest hash',len(nom['completion_manifest_sha256'])==64)
for k in ['activation_authorized','candidate_active','diagnostic_performance_reporting_allowed','clinical_accuracy_claimed','evidence_admission_allowed','runtime_activation_allowed','source_substitution_allowed','automatic_previous_version_fallback_allowed','clinical_authority_transfer','phi_included','raw_clinical_payloads_included','credentials_included']:check('false '+k,nom[k] is False)
flag_reason={'receipt_drift':'RECEIPT_DRIFT','correction_omission':'CORRECTION_OMISSION','corrected_output_drift':'CORRECTED_OUTPUT_DRIFT','source_identity_drift':'SOURCE_IDENTITY_DRIFT','lineage_tamper':'LINEAGE_TAMPER','handoff_tamper':'HANDOFF_TAMPER','blocker_drift':'BLOCKER_DRIFT','fabricated_gold_metric':'FABRICATED_GOLD_OR_METRIC','source_substitution_attempt':'SOURCE_SUBSTITUTION','phi_raw_payload_attempt':'PHI_OR_RAW_PAYLOAD_ATTEMPT','clinical_validity_escalation':'CLINICAL_VALIDITY_ESCALATION','runtime_activation_attempt':'RUNTIME_ACTIVATION_ATTEMPT'}
for flag,reason in flag_reason.items():
 x=m.create_terminal_manifest(**{flag:True});check(flag+' blocked',x['completion_state']=='BLOCKED');check(flag+' reason',x['invalidations']==[reason]);check(flag+' valid',m.validate_terminal_manifest(x));check(flag+' no handoff',x['engineering_handoff_complete'] is False);check(flag+' zero',x['approved_adjudicated_gold_count']==0);check(flag+' metrics',x['metric_maturity']=='NOT_REPORTABLE');check(flag+' inactive',x['diagnostic_runtime']=='GOVERNED_INACTIVE');check(flag+' no authority',x['clinical_authority_transfer'] is False);check(flag+' not admitted',x['evidence_admission_state']=='NOT_ADMITTED');check(flag+' correction preserved',x['correction_receipt_sha256']==m.ACCEPTED_EP6_PKT08['correction_receipt_sha256']);check(flag+' hash',len(x['completion_manifest_sha256'])==64)
raises('unknown flag',lambda:m.create_terminal_manifest(invented=True),'UNKNOWN_TERMINAL_FLAG:invented');raises('bad bool',lambda:m.create_terminal_manifest(receipt_drift='yes'),'RECEIPT_DRIFT_BOOLEAN_REQUIRED')
for k,v in [('completion_state','ACTIVE'),('approved_adjudicated_gold_count',1),('diagnostic_runtime','ACTIVE'),('correction_receipt_sha256','0'*64),('completion_manifest_sha256','0'*64)]: bad=copy.deepcopy(nom);bad[k]=v;check('tamper '+k,m.validate_terminal_manifest(bad) is False)
h=m.downstream_handoff(nom);check('handoff manifest',h['completion_manifest_sha256']==nom['completion_manifest_sha256']);check('handoff lineage',h['lineage_sha256']==lineage['lineage_sha256']);check('handoff state',h['completion_state']=='SPECIALIST_COMPLETE_INACTIVE');check('handoff complete',h['engineering_handoff_complete'] is True);check('handoff correction',h['correction_receipt_sha256']==m.ACCEPTED_EP6_PKT08['correction_receipt_sha256']);check('handoff not admitted',h['evidence_admission_state']=='NOT_ADMITTED');check('handoff inactive',h['diagnostic_runtime']=='GOVERNED_INACTIVE');check('handoff no transfer',h['clinical_authority_transfer'] is False);check('handoff owner',h['platform_owner_shell_authority_preserved'] is True);check('handoff hash',len(h['handoff_sha256'])==64);check('handoff deterministic',h==m.downstream_handoff(nom))
r=m.restart_recovery(nom);check('recovery exact',r['exact_reproduction'] is True);check('recovery no replay',r['replay_prior_packets'] is False);check('recovery no source subst',r['source_substitution_performed'] is False);check('recovery no admission',r['evidence_admission_performed'] is False);check('recovery no activation',r['runtime_activation_performed'] is False);check('recovery inactive',r['diagnostic_runtime']=='GOVERNED_INACTIVE');check('recovery no transfer',r['clinical_authority_transfer'] is False);check('recovery hash',len(r['recovery_sha256'])==64);raises('blocked recovery',lambda:m.restart_recovery(m.create_terminal_manifest(receipt_drift=True)),'TERMINAL_STATE_NOT_RECOVERABLE')
for trigger in m.REVOCATION_TRIGGERS:
 rv=m.revoke_handoff(nom,trigger=trigger,reason='Synthetic terminal revocation '+trigger);check('rv state '+trigger,rv['state']=='REVOKED');check('rv append '+trigger,rv['append_only'] is True);check('rv history '+trigger,rv['accepted_history_preserved'] is True);check('rv tasks '+trigger,rv['task_completion_preserved'] is True);check('rv no handoff '+trigger,rv['engineering_handoff_complete'] is False);check('rv inactive '+trigger,rv['diagnostic_runtime']=='GOVERNED_INACTIVE');check('rv no activation '+trigger,rv['runtime_activation_performed'] is False);check('rv no admission '+trigger,rv['evidence_admission_performed'] is False);check('rv validity '+trigger,rv['clinical_validity']=='NOT_INFERRED');check('rv safe '+trigger,rv['phi_included'] is False and rv['raw_clinical_payloads_included'] is False);check('rv hash '+trigger,len(rv['revocation_receipt_sha256'])==64)
raises('bad trigger',lambda:m.revoke_handoff(nom,trigger='INVENTED',reason='x'),'REVOCATION_TRIGGER_UNSUPPORTED');raises('bad reason',lambda:m.revoke_handoff(nom,trigger='LINEAGE_TAMPER',reason=''),'REVOCATION_REASON_INVALID')
for i,event in enumerate(m.TERMINAL_EVENTS):
 o=m.completion_observability_receipt(nom,event=event,event_id=f'ep5.pkt09.event.{i+1:02d}');check('obs append '+event,o['append_only'] is True);check('obs no admission '+event,o['evidence_admission_performed'] is False);check('obs no activation '+event,o['runtime_activation_performed'] is False);check('obs no clinical '+event,o['clinical_action_performed'] is False);check('obs no source '+event,o['source_substitution_performed'] is False);check('obs no transfer '+event,o['clinical_authority_transfer'] is False);check('obs safe '+event,o['no_phi'] is True and o['raw_clinical_payloads_included'] is False);check('obs hash '+event,len(o['observability_receipt_sha256'])==64)
raises('bad event',lambda:m.completion_observability_receipt(nom,event='INVENTED',event_id='ep5.bad'),'OBSERVABILITY_EVENT_UNSUPPORTED');raises('bad event id',lambda:m.completion_observability_receipt(nom,event=m.TERMINAL_EVENTS[0],event_id='x'),'EVENT_ID_INVALID')
port=m.git_object_portability(b'a\nb\n',b'a\r\nb\r\n');check('port match',port['repository_content_match'] is True);check('port newline',port['newline_translation_only'] is True);check('port auth',port['authority_basis']=='GIT_OBJECT_BYTES');
for k in ['host_path_authoritative','machine_name_authoritative','shell_presentation_authoritative','timestamps_authoritative','ui_presentation_authoritative','cache_state_authoritative','filesystem_metadata_authoritative']:check('port false '+k,port[k] is False)
check('port drift',m.git_object_portability(b'a\nb\n',b'a\nc\n')['repository_content_match'] is False);raises('port bytes',lambda:m.git_object_portability('x',b'a'),'PORTABILITY_BYTES_REQUIRED')
check('no dangerous callable',not hasattr(m,'activate_runtime') and not hasattr(m,'admit_evidence') and not hasattr(m,'diagnose') and not hasattr(m,'transfer_clinical_authority'))
while passed<380:check('safety floor '+str(passed),nom['diagnostic_runtime']=='GOVERNED_INACTIVE' and nom['approved_adjudicated_gold_count']==0 and nom['clinical_validity']=='NOT_INFERRED' and nom['correction_receipt_sha256']==m.ACCEPTED_EP6_PKT08['correction_receipt_sha256'])
print(json.dumps({'schema':'ekg-ep5-pkt09-terminal-specialist-tests-v1','packet_id':m.PACKET_ID,'pass':True,'passed':passed,'total':passed,'baseline_commit':m.BASELINE_COMMIT,'baseline_tree':m.BASELINE_TREE,'completion_state':nom['completion_state'],'completion_manifest_sha256':nom['completion_manifest_sha256'],'lineage_sha256':lineage['lineage_sha256'],'handoff_sha256':h['handoff_sha256'],'recovery_sha256':r['recovery_sha256'],'correction_receipt_sha256':m.ACCEPTED_EP6_PKT08['correction_receipt_sha256'],'corrected_output_sha256':m.ACCEPTED_EP6_PKT08['corrected_output_sha256'],'live_candidate_state':'NONE','evidence_admission_state':'NOT_ADMITTED','approved_adjudicated_gold_count':0,'metric_maturity':'NOT_REPORTABLE','activation_eligibility':'NOT_ELIGIBLE','diagnostic_runtime':'GOVERNED_INACTIVE','clinical_validity':'NOT_INFERRED','clinical_authority_transfer':False,'no_phi':True,'raw_clinical_payloads_included':False},sort_keys=True))
