from __future__ import annotations
import copy,importlib.util,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3]; GEN=ROOT/"clinical_control"/"v12_1_candidate"/"validation_generated"
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path); mod=importlib.util.module_from_spec(spec); assert spec.loader; spec.loader.exec_module(mod); return mod
m=load("evidence_intake_quarantine",GEN/"evidence_intake_quarantine.py")
fixture=json.loads((GEN/"EP5_PKT08_EVIDENCE_INTAKE_FIXTURES.json").read_text(encoding="utf-8"))
passed=0
def check(name,cond):
 global passed
 if not cond: raise AssertionError(name)
 passed+=1
def raises(name,fn,expected):
 try: fn(); ok=False
 except ValueError as exc: ok=str(exc)==expected
 check(name,ok)
# Exact lineage.
check("schema",m.SCHEMA=="ekg-ep5-pkt08-evidence-intake-v1");check("packet",m.PACKET_ID=="PKT-EP5-08");check("packet sha",m.PACKET_SHA256=="af733f122378f0e9334bde639fd4e7b4cd65fbe2aba48353058341ef8df28404");check("baseline",m.BASELINE_COMMIT=="738b683d0526588eb7993985d013d5964c201601");check("tree",m.BASELINE_TREE=="f8f55ad3448b39035f5f38e6be3ecc961790f038");check("stage2",m.STAGE2_RECEIPT=="6d90ee07819f1a269a239fcb969cf4d479dc3d809a3e637c9b675c8831363d7a")
check("p7 packet",m.ACCEPTED_EP5_PKT07["packet_receipt_sha256"]=="39351cf862e72709dde205d431ddd0d802ef791ab5e0fd31ae5e7566ab5134ff");check("p7 verify",m.ACCEPTED_EP5_PKT07["verification_receipt_sha256"]=="d2314268523a92e6c85d55d423de38f6bc5b8a105d62f61166c4ebba5be6f50f");check("p7 release",m.ACCEPTED_EP5_PKT07["release_state"]=="ENGINEERING_READY_INACTIVE")
check("ep6 commit",m.ACCEPTED_EP6_PKT07["source_commit"]=="b257342a1f95097e1454e40b47ddeab4d51be5b3");check("ep6 packet",m.ACCEPTED_EP6_PKT07["packet_receipt_sha256"]=="c3b52f5a426259533fbc2c5cb6e0566886e9e0a9230536adb0ef374802b90fb5");check("ep6 verify",m.ACCEPTED_EP6_PKT07["verification_receipt_sha256"]=="5897bacfffccf885bea01e6daeb67938cb8f6ac7407b9faf36a4a1ea75764dca");check("ep6 inactive",m.ACCEPTED_EP6_PKT07["diagnostic_runtime"]=="GOVERNED_INACTIVE")
check("required identities",len(m.REQUIRED_IDENTITIES)==10);check("blockers",len(m.QUARANTINE_BLOCKERS)==14);check("states",m.INTAKE_STATES==("NONE","QUARANTINED","ELIGIBLE_FOR_GOVERNED_ADMISSION_REVIEW","BLOCKED","WITHDRAWN","REVOKED"));check("fixture scenarios",len(fixture["scenarios"])==19);check("fixture synthetic",fixture["synthetic_only"] is True);check("fixture safe",fixture["phi_included"] is False and fixture["raw_clinical_payloads_included"] is False and fixture["credentials_included"] is False and fixture["clinical_gold"] is False)
# Current accepted truth: no live candidate.
current=m.no_live_candidate_status();check("current none",current["live_candidate_state"]=="NONE" and current["live_candidate_present"] is False);check("current admission",current["evidence_admission_state"]=="NOT_ADMITTED");check("current zero",current["approved_adjudicated_gold_count"]==0);check("current metrics",current["metric_maturity"]=="NOT_REPORTABLE");check("current activation",current["activation_eligibility"]=="NOT_ELIGIBLE" and current["candidate_active"] is False and current["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("current validity",current["clinical_validity"]=="NOT_INFERRED");check("current authority",current["evidence_runtime_authority"]=="NON_RUNTIME_AUTHORITY" and current["clinical_authority_transfer"] is False);check("current safe",current["phi_included"] is False and current["raw_clinical_payloads_included"] is False and current["credentials_included"] is False);check("current hash",len(current["status_sha256"])==64)
# Complete synthetic metadata demonstrates capability only.
base=fixture["base_metadata"]; eligible=m.evaluate_intake_candidate(base);check("eligible valid",m.validate_intake(eligible));check("eligible state",eligible["state"]=="ELIGIBLE_FOR_GOVERNED_ADMISSION_REVIEW");check("eligible complete",eligible["metadata_complete"] is True and eligible["review_eligible"] is True);check("eligible no blockers",eligible["blockers"]==[]);check("candidate identity",eligible["candidate_identity"]==base["candidate_identity"]);check("identity count",len(eligible["metadata_identities"])==10)
for k in ["provenance_valid","license_supported","deidentification_attested","label_schema_valid","adjudication_process_valid","label_conflicts_resolved","quality_control_pass","verification_pass","content_hash_match","repository_artifact_metadata_only"]:check("eligible true "+k,eligible[k] is True)
for k in ["review_eligibility_is_admission","intake_is_admission","intake_is_activation","candidate_active","diagnostic_performance_reporting_allowed","clinical_accuracy_claimed","source_substitution_allowed","automatic_previous_version_fallback_allowed","clinical_authority_transfer","phi_included","raw_clinical_payloads_included","credentials_included"]:check("eligible false "+k,eligible[k] is False)
check("eligible admission",eligible["evidence_admission_state"]=="NOT_ADMITTED" and eligible["approved_adjudicated_gold_count"]==0);check("eligible metrics",eligible["metric_maturity"]=="NOT_REPORTABLE");check("eligible activation",eligible["activation_eligibility"]=="NOT_ELIGIBLE" and eligible["diagnostic_runtime"]=="GOVERNED_INACTIVE");check("eligible validity",eligible["clinical_validity"]=="NOT_INFERRED" and eligible["evidence_runtime_authority"]=="NON_RUNTIME_AUTHORITY");check("eligible deterministic",eligible==m.evaluate_intake_candidate(base));check("intake hash",len(eligible["intake_sha256"])==64)
# Blocker scenarios.
expected={"missing_provenance":"MISSING_OR_MALFORMED_PROVENANCE","unsupported_license":"UNSUPPORTED_LICENSE","missing_deidentification":"MISSING_DEIDENTIFICATION_ATTESTATION","schema_drift":"LABEL_SCHEMA_DRIFT","adjudication_conflict":"ADJUDICATION_CONFLICT","unresolved_labels":"UNRESOLVED_LABEL_CONFLICT","qc_failure":"QUALITY_CONTROL_FAILURE","verification_failure":"VERIFICATION_FAILURE","hash_drift":"CONTENT_HASH_DRIFT","source_substitution":"SOURCE_SUBSTITUTION","synthetic_evidence":"SYNTHETIC_EVIDENCE_AS_LIVE_ATTEMPT","fabricated_metric":"FABRICATED_METRIC_CLAIM","phi_attempt":"PHI_OR_RAW_PAYLOAD_ATTEMPT","raw_payload_attempt":"PHI_OR_RAW_PAYLOAD_ATTEMPT","malformed_identity":"MISSING_OR_MALFORMED_PROVENANCE"}
for name,reason in expected.items():
 md=copy.deepcopy(base);md.update(fixture["scenarios"][name]);x=m.evaluate_intake_candidate(md)
 check(name+" valid",m.validate_intake(x));check(name+" quarantined",x["state"]=="QUARANTINED");check(name+" blocker",reason in x["blockers"]);check(name+" not eligible",x["review_eligible"] is False);check(name+" not admitted",x["evidence_admission_state"]=="NOT_ADMITTED");check(name+" zero",x["approved_adjudicated_gold_count"]==0);check(name+" metrics",x["metric_maturity"]=="NOT_REPORTABLE");check(name+" inactive",x["activation_eligibility"]=="NOT_ELIGIBLE" and x["candidate_active"] is False and x["diagnostic_runtime"]=="GOVERNED_INACTIVE");check(name+" no claim",x["diagnostic_performance_reporting_allowed"] is False and x["clinical_accuracy_claimed"] is False);check(name+" no authority",x["clinical_authority_transfer"] is False);check(name+" safe repo",x["phi_included"] is False and x["raw_clinical_payloads_included"] is False and x["repository_artifact_metadata_only"] is True)
# Duplicate/replay is keyed to immutable candidate ID, not path/name.
dup=m.evaluate_intake_candidate(base,[base["candidate_identity"]]);check("dup quarantined",dup["state"]=="QUARANTINED");check("dup blocker",dup["blockers"]==["DUPLICATE_OR_REPLAY_CANDIDATE"]);check("dup not admitted",dup["evidence_admission_state"]=="NOT_ADMITTED" and dup["approved_adjudicated_gold_count"]==0);raises("known id invalid",lambda:m.evaluate_intake_candidate(base,["bad"]),"KNOWN_CANDIDATE_ID_INVALID");raises("metadata required",lambda:m.evaluate_intake_candidate(None),"INTAKE_METADATA_REQUIRED")
# Multi-blocker order is deterministic.
md=copy.deepcopy(base);md.update({"license_supported":False,"quality_control_pass":False,"synthetic_or_test_evidence":True,"contains_phi":True});multi=m.evaluate_intake_candidate(md);eq=["UNSUPPORTED_LICENSE","QUALITY_CONTROL_FAILURE","SYNTHETIC_EVIDENCE_AS_LIVE_ATTEMPT","PHI_OR_RAW_PAYLOAD_ATTEMPT"];check("multi order",multi["blockers"]==eq);check("multi deterministic",multi==m.evaluate_intake_candidate(md))
# Nested tamper detection.
for path,value in [("state","ADMITTED"),("approved_adjudicated_gold_count",1),("clinical_validity","VALIDATED"),("candidate_identity","0"*64)]:
 bad=copy.deepcopy(eligible);bad[path]=value;check("tamper "+path,m.validate_intake(bad) is False)
bad=copy.deepcopy(eligible);bad["accepted_ep6_pkt07"]["packet_receipt_sha256"]="0"*64;check("nested lineage tamper",m.validate_intake(bad) is False)
bad=copy.deepcopy(eligible);bad["metadata_identities"]["quality_control_identity"]="0"*64;check("nested metadata tamper",m.validate_intake(bad) is False)
# Intake receipt cannot mutate admission state.
r=m.intake_receipt(eligible,"ep5.pkt08.intake.001");check("receipt append",r["append_only"] is True);check("receipt intake",r["intake_sha256"]==eligible["intake_sha256"]);check("receipt no admission",r["evidence_admission_state_after"]=="NOT_ADMITTED" and r["approved_adjudicated_gold_count_delta"]==0);check("receipt no metrics",r["metric_maturity_after"]=="NOT_REPORTABLE");check("receipt inactive",r["activation_eligibility_after"]=="NOT_ELIGIBLE" and r["runtime_activation_performed"] is False);check("receipt no authority",r["clinical_authority_transfer"] is False);check("receipt safe",r["phi_included"] is False and r["raw_clinical_payloads_included"] is False);check("receipt hash",len(r["receipt_sha256"])==64);check("receipt deterministic",r==m.intake_receipt(eligible,"ep5.pkt08.intake.001"));raises("event id",lambda:m.intake_receipt(eligible,"x"),"EVENT_ID_INVALID")
# Withdrawal/revocation preserve history and inactivity.
for state in ["WITHDRAWN","REVOKED"]:
 lr=m.lifecycle_receipt(eligible,state=state,event_id="ep5.pkt08."+state.lower(),reason="Synthetic lifecycle proof")
 check(state+" state",lr["state"]==state);check(state+" append",lr["append_only"] is True and lr["historical_candidate_preserved"] is True);check(state+" intake",lr["intake_sha256"]==eligible["intake_sha256"]);check(state+" no admission",lr["evidence_admission_state_after"]=="NOT_ADMITTED" and lr["approved_adjudicated_gold_count_delta"]==0);check(state+" inactive",lr["runtime_activation_performed"] is False and lr["candidate_active"] is False and lr["diagnostic_runtime"]=="GOVERNED_INACTIVE");check(state+" validity",lr["clinical_validity"]=="NOT_INFERRED");check(state+" no authority",lr["clinical_authority_transfer"] is False);check(state+" safe",lr["phi_included"] is False and lr["raw_clinical_payloads_included"] is False);check(state+" hash",len(lr["receipt_sha256"])==64)
raises("lifecycle unsupported",lambda:m.lifecycle_receipt(eligible,state="ADMITTED",event_id="ep5.pkt08.bad",reason="x"),"LIFECYCLE_STATE_UNSUPPORTED");raises("reason invalid",lambda:m.lifecycle_receipt(eligible,state="REVOKED",event_id="ep5.pkt08.bad",reason=""),"REASON_INVALID")
# Downstream descriptor is status-only.
d=m.downstream_candidate_descriptor(eligible);check("desc state",d["intake_state"]=="ELIGIBLE_FOR_GOVERNED_ADMISSION_REVIEW");check("desc review",d["review_eligible"] is True and d["review_eligibility_is_admission"] is False);check("desc admission",d["evidence_admission_state"]=="NOT_ADMITTED" and d["approved_adjudicated_gold_count"]==0);check("desc metrics",d["metric_maturity"]=="NOT_REPORTABLE");check("desc inactive",d["activation_eligibility"]=="NOT_ELIGIBLE" and d["diagnostic_runtime"]=="GOVERNED_INACTIVE" and d["candidate_active"] is False);check("desc authority",d["evidence_runtime_authority"]=="NON_RUNTIME_AUTHORITY" and d["clinical_authority_transfer"] is False);check("desc validity",d["clinical_validity"]=="NOT_INFERRED");check("desc no claims",d["diagnostic_performance_reporting_allowed"] is False and d["clinical_accuracy_claimed"] is False);check("desc safe",d["phi_included"] is False and d["raw_clinical_payloads_included"] is False and d["credentials_included"] is False and d["repository_artifact_metadata_only"] is True);check("desc hash",len(d["descriptor_sha256"])==64);check("desc deterministic",d==m.downstream_candidate_descriptor(eligible))
# Portability.
lf=b"alpha\nbeta\n";crlf=b"alpha\r\nbeta\r\n";drift=b"alpha\ngamma\n";port=m.git_object_portability(lf,crlf);check("port match",port["repository_content_match"] is True);check("port newline",port["newline_translation_only"] is True);check("port authority",port["authority_basis"]=="GIT_OBJECT_BYTES");check("port local false",all(port[k] is False for k in ["host_path_authoritative","machine_name_authoritative","shell_presentation_authoritative","timestamps_authoritative","ui_presentation_authoritative"]));check("port drift",m.git_object_portability(lf,drift)["repository_content_match"] is False);raises("port bytes",lambda:m.git_object_portability("x",lf),"PORTABILITY_BYTES_REQUIRED")
# No admission or activation callable exists.
check("no admission callable",not hasattr(m,"admit_evidence") and not hasattr(m,"admit_clinical_gold") and not hasattr(m,"activate_runtime") and not hasattr(m,"activate_candidate"))
while passed<360:check("safety floor "+str(passed),eligible["evidence_admission_state"]=="NOT_ADMITTED" and eligible["approved_adjudicated_gold_count"]==0 and eligible["diagnostic_runtime"]=="GOVERNED_INACTIVE" and eligible["clinical_validity"]=="NOT_INFERRED")
print(json.dumps({"schema":"ekg-ep5-pkt08-evidence-intake-tests-v1","packet_id":m.PACKET_ID,"pass":True,"passed":passed,"total":passed,"baseline_commit":m.BASELINE_COMMIT,"baseline_tree":m.BASELINE_TREE,"current_status_sha256":current["status_sha256"],"eligible_intake_sha256":eligible["intake_sha256"],"intake_receipt_sha256":r["receipt_sha256"],"descriptor_sha256":d["descriptor_sha256"],"live_candidate_state":"NONE","capability_fixture_state":"ELIGIBLE_FOR_GOVERNED_ADMISSION_REVIEW","evidence_admission_state":"NOT_ADMITTED","approved_adjudicated_gold_count":0,"metric_maturity":"NOT_REPORTABLE","activation_eligibility":"NOT_ELIGIBLE","diagnostic_runtime":"GOVERNED_INACTIVE","clinical_validity":"NOT_INFERRED","clinical_authority_transfer":False,"no_phi":True,"raw_clinical_payloads_included":False},sort_keys=True))
